#此配置文件中的内容为nacos配置列表中的内容
#此文件本身并无作用，实际项目中可以删除，仅为了方便大家复制粘贴
server:
  port: 9998
spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
      routes:  # 路由
        - id: order-service #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://order-service # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/order/** # 断言，路径相匹配进行路由
        - id: point-service #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://point-service # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/point/** # 断言，路径相匹配进行路由
        - id: user-service #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://user-service # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/user/** # 断言，路径相匹配进行路由
config:
  redisTimeout: 60