#此配置文件中的内容为nacos配置列表中的内容
#此文件本身并无作用，实际项目中可以删除，仅为了方便大家复制粘贴
server:
  port: 9080
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: localhost  # Redis服务器地址
    port: 6379       # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码(如果设置了)
config:
  info: 这是order-service，端口号9080，哈哈

